"""Markets: catalogue, exact settlement, pricing and selection."""

from foot.markets.catalogue import (
    MarketFamily,
    MarketOffer,
    UnsupportedMarketError,
    asian_handicap,
    both_teams_to_score,
    correct_score_group,
    double_chance,
    draw_no_bet,
    match_result,
    refuse_if_unsupported,
    standard_catalogue,
    team_total,
    total_goals,
)
from foot.markets.pricing import (
    GridDiagnostics,
    PricedOffer,
    grid_diagnostics,
    price_catalogue,
    price_offer,
)
from foot.markets.selection import (
    Confidence,
    Decision,
    DecisionStatus,
    RankingCriteria,
    Scenario,
    ScoredOffer,
    select_best,
)
from foot.markets.settlement import Settlement, SettlementProfile, unit_return

__all__ = [
    "Confidence",
    "Decision",
    "DecisionStatus",
    "GridDiagnostics",
    "MarketFamily",
    "MarketOffer",
    "PricedOffer",
    "RankingCriteria",
    "Scenario",
    "ScoredOffer",
    "Settlement",
    "SettlementProfile",
    "UnsupportedMarketError",
    "asian_handicap",
    "both_teams_to_score",
    "correct_score_group",
    "double_chance",
    "draw_no_bet",
    "grid_diagnostics",
    "match_result",
    "price_catalogue",
    "price_offer",
    "refuse_if_unsupported",
    "select_best",
    "standard_catalogue",
    "team_total",
    "total_goals",
    "unit_return",
]
